name: garbigo_frontend
description: A Garbage Management System - Garbigo
publish_to: 'none' # Prevents accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.0.3

  # Navigation & Routing
  go_router: ^17.0.0

  # Networking
  http: ^1.6.0
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.5.3

  # Authentication
  google_sign_in: ^7.2.0

  # Image Handling
  image_picker: ^1.2.1
  cached_network_image: ^3.4.1

  # Environment Variables
  flutter_dotenv: ^6.0.0

  # UI Enhancements
  flutter_spinkit: ^5.2.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - .env
    - assets/images/