name: garbigo_frontend
description: Garbigo Garbage Collection Flutter Frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # HTTP
  dio: ^5.5.0

  # Navigation
  go_router: ^14.2.7

  # Social Login
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  sign_in_with_apple: ^6.1.0

  # Image Picker
  image_picker: ^1.1.2

  # Storage
  shared_preferences: ^2.3.2

  # Utils
  fluttertoast: ^8.2.6
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  google_maps_flutter: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/